### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by davidkarlsen** [novumrgi/helm#6]
We already have a helm chart for dependency-track at https://github.com/evryfs/helm-charts/tree/master/charts/dependency-track -  would you rather want to join forces on that one?

**Comment by luhahn** [comment]
Hi @davidkarlsen, i was rather busy the last few days. Sure, we'd like to join forces :) 

Since your chart is already linked from the readme i guess we should move to the already existing one?

**Comment by davidkarlsen** [comment]
I think that make sense - you can do PRs against it if something is missing? Then we get one chart with two efforts around it.

**Comment by luhahn** [comment]
What do you think about the config part.
It creates a application.properties automatically, this is used instead of the environment variables. The advantage here is, that
we don't need to add anything else, because it is completly generated. Even though new values are added.
Also the users don't need to create the file themselves with a huge string.

```yaml
config:
    alpine:
      worker:
        threads: 0
        thread:
          multiplier: 4

      data:
        directory: /data

      watchdog:
        logging:
          interval: 0

      database:
        pool:
          enabled: true
          max:
            size: 10
            lifetime: 600000
          idle:
            timeout: 600000

      enforce:
        authentification: true
        authorization: true

      bcrypt:
        rounds: 14
```
