### ISSUE TITLE
Task resource requests which are not divisible evenly by 100 or 1000 are rounded to 0, causing awx system task queues to have 0 capacity and not execute any tasks.

### ISSUE THREAD

**Issue by a7l** [novumrgi/helm#7]
Since Helm does not support floating-point division in arithmetic, depending on the resource requests set for the task runner in the values.yml file, a 0 is printed in the CPU and MEM max values in the settings.py file below:

https://github.com/novumrgi/helm/blob/6c44abe8d90a29f4abdbccbd92a830e093e1ec99/charts/awx/templates/awx/configmaps/config.yaml#L121

A workaround to this issue might be to assign default values in case the `div` operator returns a zero, e.g. add `| max 4` and `| max 100` as below:

```
    SYSTEM_TASK_ABS_CPU = {{ required "Value required: .Values.resources.task.requests.cpu" .Values.resources.task.requests.cpu | replace "m" "" | div 1000 | mul 4 | int | max 4 }}
    SYSTEM_TASK_ABS_MEM = {{ required "Value required: .Values.resources.task.requests.memory" .Values.resources.task.requests.memory | replace "Mi" "" | div 100 | int | max 100 }}
```

**Comment by luhahn** [comment]
Thanks for reporting that issue, i will have a look at it

**Comment by luhahn** [comment]
@a7l  This should be fixed now. 
I've added a new way to calculate the values. It will now always round down to the next full number, example 4900m for cpu will result in 16 as calculated value.

You can also set the values directly now, instead of using the auto generation.

```yaml
awx:
  settings:
    # will override the auto generated value from resources
    systemTaskAbsCpu:
    # will override the auto generated value from resources
    systemTaskAbsMem:
```
